### ISSUE TITLE
problemas con el pom.xml

### ISSUE THREAD

**Issue by kmax14** [oeg-upm/map4rdf#33]
Después de haber buscado en muchas páginas, sigo teniendo un problema en el parent. Esto me pasa después de importar el proyecto maven en eclipse. Es la primera vez que hago esto y la verdad que creo que tengo un problema de conceptos pero no consigo solucionarlo.
![fallo pom 1](https://user-images.githubusercontent.com/32069970/51627138-8539be00-1f41-11e9-9258-bddd7fd4e40c.JPG)
![fallo pom 2](https://user-images.githubusercontent.com/32069970/51627139-8539be00-1f41-11e9-87b3-3065cf38cc86.png)

Gracias

**Comment by Fransiro** [comment]
Eso se debe a que Map4RDF hereda de un pom del grupo OEG. Ese pom padre
tiene sus dependencias y sus librerías y lo tienes cacheado en tu local
pero como Maven refresca esa cache entonces vuelve a preguntar a los
repositorios para encontrar el pom.xml de ese artifact (padre) y no lo
encuentra porque están caidos.
Si miras el fichero pom.xml de map4rdf veras que el padre es este:
<parent>
<artifactId>parent-pom-os</artifactId>
<groupId>es.upm.oeg</groupId>
<version>1.0</version>
</parent>

Y si miras más abajo veras que las URL de los repositorios maven del grupo
OEG para descargar ese padre son:
http://oeg-dev.dia.fi.upm.es/maven/public/
http://oeg-dev.dia.fi.upm.es:8081/nexus/content/repositories/map4rdf_maven/

Las dos rutas están caidas y no funciona el servidor, por eso te salta ese
error.

Igualmente ese error no debería impedir el funcionamiento del compilado
mientras mantengas tu copia en cache del fichero pom.xml del padre. Si
alguna vez cambias de ordenador o limpias la cache (fichero .m2 en tu
carpeta personal) entonces si que no funcionara el compilado de map4rdf.

Un saludo.

**Comment by kmax14** [comment]
Buenas te comento, 

He probado a pinchar en los enlaces y no me funciona niniguno, nose si estaran caidos. Despues he provado a comentar al padre para que no me diera ese error y ya no me sale ningun error en el pom pero en el overview me salen varios errores de que falla al leer algun artifact (pongo foto debajo) y entonces no me deja compilar y generar el archivo para meter al servidor.

Por otro lado comentarte que necesito arrancar el codigo y probarlo ya que es parte de mi TFG y necesito primero comprobar que funciona y ya despues hacer los cambios pertinentes y poder empezar mis pruebas. Por eso me gustaria poder arreglar el problema lo antes posible.

Muchas gracias.
![fallo enlace 1](https://user-images.githubusercontent.com/32069970/52143558-2caea300-265c-11e9-92a8-33a0e10b4e1b.png)
![fallo enlace 2](https://user-images.githubusercontent.com/32069970/52143559-2caea300-265c-11e9-8b38-48200ad8a46b.png)
![fallo overview](https://user-images.githubusercontent.com/32069970/52143561-2d473980-265c-11e9-90b3-1e6cc09e0a4c.png)

**Comment by Fransiro** [comment]
La única solución que te puedo ofrecer para quitar ese error de eclipse es que vuelvan a levantar el servidor.
Yo no tengo permisos y ya no trabajo en el laboratorio así que en este caso no te puedo ayudar.
Tendrías que contactar con el laboratorio OEG de la UPM para que vuelvan a levantar el servidor.

Otra solución es que te crees un repositorio propio y subas el parent pom que tienes en local.

Un saludo.

**Comment by ocorcho** [comment]
Assigned to @ralcazar-oeg

**Comment by ralcazar-oeg** [comment]
Solucionado problema de acceso a la url
http://oeg-dev.dia.fi.upm.es/maven/public/

**Comment by kmax14** [comment]
Me sigue dando error porque depende de la otra URL. El problema es este: 

Project build error: Non-resolvable parent POM for es.upm.oeg.geolinkeddata:map4rdf:0.0.5-OL-SNAPSHOT: Failure to transfer es.upm.oeg:parent-pom-os:pom:1.0 from http://oeg-dev.dia.fi.upm.es:8081/nexus/content/repositories/map4rdf_maven/ was cached in the local repository, resolution will not be reattempted until the update interval of map4rdf_maven has elapsed or updates are forced. Original error: Could not transfer artifact es.upm.oeg:parent-pom-os:pom:1.0 from/to map4rdf_maven (http://oeg-dev.dia.fi.upm.es:8081/nexus/content/repositories/map4rdf_maven/): connect timed out and 'parent.relativePath' points at wrong local POM

De todas formas voy a probar a compilar y probar en local si funciona.

**Comment by ralcazar-oeg** [comment]
Hola
El firewall tenía bloqueado el puerto 8081 y el entutamiento de nexus al puerto 80 no es correcto. 
Como veo que el código está asociado a la url con el puerto he abierto el puerto 8081, que te permitirá acceder a los repositorios públicos.

**Comment by kmax14** [comment]
Buenas, ya no me da ningun error pero creo que tengo mal configurado el plugin gwt. HE visto que que instalarlo y he seguido los pasos para ello pero cuando intento hacer maven install me da este error y pienso que es por este plugin.

![error gwt](https://user-images.githubusercontent.com/32069970/53039680-f789b980-347f-11e9-9541-ca3405e48333.PNG)

otra opción que se me ocurre es pasarme por el laboratorio de la facultad si hubiera alguien y que me echaran una mano.

Gracias.

**Comment by Fransiro** [comment]
Seria necesario más información de tu entorno de desarrollo para poder detectar el error ya que he probado en varios entornos y a mi me funciona la compilación.
¿Has tratado de ejecutar el comando (que aparece en el log) en el terminal de windows? A lo mejor nos da más información. El comando esta en la segunda linea que empieza por "[ERROR]" (toda la linea, que en la captura se corta)
Igualmente si saco un rato libre intentare crear 2 maquinas virtuales una en windows y otra en linux como entorno de desarrollo para que sea más fácil programar en map4rdf.

**Comment by Fransiro** [comment]
Ya he generado la maquina virtual y ya esta publicada en un servidor del laboratorio.

El enlace de descarga es el siguiente: https://delicias.dia.fi.upm.es/nextcloud/index.php/s/mbm68W6wFKTF9dC

Y tienes una mini guia de como instalar la Maquina Virtual aquí:
https://github.com/oeg-upm/map4rdf/wiki/Virtual-Machine-for-development-Map4RDF

Espero que este contenido te sirva de ayuda.

Un saludo.

**Comment by kmax14** [comment]
Buenas, intento entrar en la maquina virtual y me pide una contraseña que no me se.

**Comment by Fransiro** [comment]
En la wiki que te pase (Te vuelvo a pasar el enlace: https://github.com/oeg-upm/map4rdf/wiki/Virtual-Machine-for-development-Map4RDF) en la sección "Run Virtual Machine" tienes el usuario y contraseña de Windows para acceder.
